"""Create trials table

Revision ID: 4657c26a5915
Revises: 
Create Date: 2026-02-08 16:55:07.061312

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4657c26a5915'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_trial_metadata_id', table_name='trial_metadata')
    op.drop_table('trial_metadata')
    op.drop_index('ix_eligibility_criteria_id', table_name='eligibility_criteria')
    op.drop_table('eligibility_criteria')
    op.add_column('trials', sa.Column('distance', sa.Integer(), nullable=False))
    op.add_column('trials', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('trials', sa.Column('why_matched', sa.JSON(), nullable=False))
    op.add_column('trials', sa.Column('what_to_confirm', sa.JSON(), nullable=False))
    op.add_column('trials', sa.Column('eligibility_criteria', sa.JSON(), nullable=False))
    op.add_column('trials', sa.Column('burden', sa.JSON(), nullable=False))
    op.add_column('trials', sa.Column('exclusion_risks', sa.JSON(), nullable=False))
    op.add_column('trials', sa.Column('translated_info', sa.JSON(), nullable=False))
    op.alter_column('trials', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('trials', 'phase',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('trials', 'sponsor',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('trials', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('trials', 'location',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('trials', 'cancer_type',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('trials', 'last_updated',
               existing_type=sa.DATE(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('trials', 'created_at',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('trials', 'eligibility_score',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('trials', 'match_confidence',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.drop_index('ix_trials_id', table_name='trials')
    op.create_index(op.f('ix_trials_cancer_type'), 'trials', ['cancer_type'], unique=False)
    op.drop_column('trials', 'distance_miles')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trials', sa.Column('distance_miles', sa.INTEGER(), nullable=True))
    op.drop_index(op.f('ix_trials_cancer_type'), table_name='trials')
    op.create_index('ix_trials_id', 'trials', ['id'], unique=False)
    op.alter_column('trials', 'match_confidence',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('trials', 'eligibility_score',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('trials', 'created_at',
               existing_type=sa.DateTime(),
               type_=sa.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('trials', 'last_updated',
               existing_type=sa.String(),
               type_=sa.DATE(),
               existing_nullable=False)
    op.alter_column('trials', 'cancer_type',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('trials', 'location',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('trials', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('trials', 'sponsor',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('trials', 'phase',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('trials', 'id',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.drop_column('trials', 'translated_info')
    op.drop_column('trials', 'exclusion_risks')
    op.drop_column('trials', 'burden')
    op.drop_column('trials', 'eligibility_criteria')
    op.drop_column('trials', 'what_to_confirm')
    op.drop_column('trials', 'why_matched')
    op.drop_column('trials', 'updated_at')
    op.drop_column('trials', 'distance')
    op.create_table('eligibility_criteria',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('trial_id', sa.INTEGER(), nullable=False),
    sa.Column('criterion', sa.TEXT(), nullable=False),
    sa.Column('category', sa.VARCHAR(length=50), nullable=True),
    sa.Column('required', sa.BOOLEAN(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['trial_id'], ['trials.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_eligibility_criteria_id', 'eligibility_criteria', ['id'], unique=False)
    op.create_table('trial_metadata',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('trial_id', sa.INTEGER(), nullable=False),
    sa.Column('field_name', sa.VARCHAR(length=100), nullable=True),
    sa.Column('field_value', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['trial_id'], ['trials.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_trial_metadata_id', 'trial_metadata', ['id'], unique=False)
    # ### end Alembic commands ###
