"""
PDF generation for clinician briefs
Based on TrialScout PRD v1.0 specifications
"""

from reportlab.lib.pagesizes import letter
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle
from reportlab.lib import colors
from reportlab.lib.enums import TA_LEFT, TA_CENTER
from io import BytesIO
from datetime import datetime
import base64

from app.schemas import PatientProfile, MatchedTrial
from typing import List


class ClinicianBriefGenerator:
    """Generate PDF clinician briefs"""
    
    def __init__(self):
        """Initialize PDF generator"""
        self.styles = getSampleStyleSheet()
        self._setup_custom_styles()
    
    def _setup_custom_styles(self):
        """Setup custom paragraph styles"""
        # Title style
        if 'CustomTitle' not in self.styles:
            self.styles.add(ParagraphStyle(
                name='CustomTitle',
                parent=self.styles['Heading1'],
                fontSize=18,
                textColor=colors.HexColor('#1a1a1a'),
                spaceAfter=6,
                alignment=TA_CENTER
            ))
        
        # Subtitle style
        if 'CustomSubtitle' not in self.styles:
            self.styles.add(ParagraphStyle(
                name='CustomSubtitle',
                parent=self.styles['Normal'],
                fontSize=10,
                textColor=colors.HexColor('#666666'),
                spaceAfter=20,
                alignment=TA_CENTER
            ))
        
        # Section header style
        if 'SectionHeader' not in self.styles:
            self.styles.add(ParagraphStyle(
                name='SectionHeader',
                parent=self.styles['Heading2'],
                fontSize=12,
                textColor=colors.HexColor('#2c3e50'),
                spaceAfter=8,
                spaceBefore=12
            ))
        
        # Body text style - use existing BodyText if available
        if 'BodyText' not in self.styles:
            self.styles.add(ParagraphStyle(
                name='BodyText',
                parent=self.styles['Normal'],
                fontSize=9,
                leading=12
            ))
    
    def generate_brief(
        self,
        patient_profile: PatientProfile,
        matched_trials: List[MatchedTrial],
        top_n: int = 5,
        dataset_version: str = "1.0"
    ) -> bytes:
        """
        Generate clinician brief PDF
        
        Args:
            patient_profile: Patient's clinical profile
            matched_trials: List of matched trials
            top_n: Number of top trials to include
            dataset_version: Version of trial dataset
            
        Returns:
            PDF bytes
        """
        buffer = BytesIO()
        doc = SimpleDocTemplate(
            buffer,
            pagesize=letter,
            rightMargin=0.75*inch,
            leftMargin=0.75*inch,
            topMargin=0.75*inch,
            bottomMargin=0.75*inch
        )
        
        # Build document content
        story = []
        
        # Header
        story.extend(self._build_header())
        
        # Patient profile section
        story.extend(self._build_patient_profile(patient_profile))
        
        # Matched trials section
        story.extend(self._build_matched_trials(matched_trials[:top_n]))
        
        # Footer
        story.extend(self._build_footer(dataset_version))
        
        # Build PDF
        doc.build(story)
        
        # Get PDF bytes
        pdf_bytes = buffer.getvalue()
        buffer.close()
        
        return pdf_bytes
    
    def _build_header(self) -> List:
        """Build document header"""
        elements = []
        
        # Title
        title = Paragraph(
            "Clinical Trial Matching Report",
            self.styles['CustomTitle']
        )
        elements.append(title)
        
        # Subtitle
        subtitle = Paragraph(
            f"Generated by TrialScout | {datetime.now().strftime('%B %d, %Y')}",
            self.styles['CustomSubtitle']
        )
        elements.append(subtitle)
        
        return elements
    
    def _build_patient_profile(self, patient: PatientProfile) -> List:
        """Build patient profile section"""
        elements = []
        
        # Section header
        header = Paragraph("Patient Profile", self.styles['SectionHeader'])
        elements.append(header)
        
        # Demographics
        demographics = f"<b>Demographics:</b> Age {patient.age or 'Not provided'}, {patient.sex or 'Not provided'}"
        elements.append(Paragraph(demographics, self.styles['BodyText']))
        elements.append(Spacer(1, 6))
        
        # Diagnosis
        diagnosis = f"<b>Diagnosis:</b> {patient.cancer_type.title()} Cancer, Stage {patient.stage}"
        elements.append(Paragraph(diagnosis, self.styles['BodyText']))
        elements.append(Spacer(1, 6))
        
        # ECOG
        ecog_text = str(patient.ecog) if patient.ecog is not None else "Unknown"
        ecog = f"<b>ECOG Performance Status:</b> {ecog_text}"
        elements.append(Paragraph(ecog, self.styles['BodyText']))
        elements.append(Spacer(1, 6))
        
        # Biomarkers
        if patient.biomarkers:
            biomarker_list = []
            for name, status in patient.biomarkers.items():
                status_text = status.status.title()
                if status.subtype:
                    status_text += f" ({status.subtype})"
                biomarker_list.append(f"{name}: {status_text}")
            
            biomarkers = f"<b>Key Biomarkers:</b> {', '.join(biomarker_list)}"
            elements.append(Paragraph(biomarkers, self.styles['BodyText']))
            elements.append(Spacer(1, 6))
        
        # Prior treatments
        if patient.prior_therapies:
            therapies = f"<b>Prior Treatments:</b> {', '.join(patient.prior_therapies)}"
            elements.append(Paragraph(therapies, self.styles['BodyText']))
            elements.append(Spacer(1, 6))
        
        # Current line
        if patient.current_line:
            line = f"<b>Current Line of Therapy:</b> {patient.current_line.replace('-', ' ').title()}"
            elements.append(Paragraph(line, self.styles['BodyText']))
        
        elements.append(Spacer(1, 12))
        
        return elements
    
    def _build_matched_trials(self, trials: List[MatchedTrial]) -> List:
        """Build matched trials section"""
        elements = []
        
        # Section header
        header = Paragraph(
            f"Matched Trials (Top {len(trials)})",
            self.styles['SectionHeader']
        )
        elements.append(header)
        elements.append(Spacer(1, 6))
        
        # Each trial
        for i, matched_trial in enumerate(trials, 1):
            trial = matched_trial.trial
            
            # Trial title and NCT
            title_text = f"<b>{i}. {trial.title}</b> (NCT: {trial.nct_number})"
            elements.append(Paragraph(title_text, self.styles['BodyText']))
            elements.append(Spacer(1, 4))
            
            # Trial details
            details = f"Phase {trial.phase or 'N/A'} | {trial.sponsor or 'N/A'} | {trial.status.replace('_', ' ').title()}"
            elements.append(Paragraph(details, self.styles['BodyText']))
            elements.append(Spacer(1, 4))
            
            # Location
            if trial.location:
                location_text = f"<b>Location:</b> {trial.location}"
                if trial.distance_miles:
                    location_text += f", {trial.distance_miles} miles"
                elements.append(Paragraph(location_text, self.styles['BodyText']))
                elements.append(Spacer(1, 4))
            
            # Match score and confidence
            score_text = f"<b>Match Score:</b> {matched_trial.score}/100 | <b>Confidence:</b> {matched_trial.confidence.title()}"
            elements.append(Paragraph(score_text, self.styles['BodyText']))
            elements.append(Spacer(1, 6))
            
            # Why matched
            if matched_trial.why_matched:
                elements.append(Paragraph("<b>Why Matched:</b>", self.styles['BodyText']))
                for reason in matched_trial.why_matched:
                    reason_text = f"• {reason.criterion}: {reason.description}"
                    elements.append(Paragraph(reason_text, self.styles['BodyText']))
                elements.append(Spacer(1, 4))
            
            # What to confirm
            if matched_trial.what_to_confirm:
                elements.append(Paragraph("<b>What to Confirm:</b>", self.styles['BodyText']))
                for item in matched_trial.what_to_confirm:
                    item_text = f"• {item.item}: {item.description}"
                    elements.append(Paragraph(item_text, self.styles['BodyText']))
                elements.append(Spacer(1, 4))
            
            # Patient burden
            burden = matched_trial.patient_burden
            if any(burden.values()):
                burden_parts = []
                if burden.get("visits_per_month"):
                    burden_parts.append(f"{burden['visits_per_month']} visits/month")
                if burden.get("imaging_frequency"):
                    burden_parts.append(f"Imaging: {burden['imaging_frequency']}")
                if burden.get("biopsy_required"):
                    burden_parts.append("Biopsy required")
                if burden.get("hospital_stays"):
                    burden_parts.append("Hospital stays required")
                
                if burden_parts:
                    burden_text = f"<b>Patient Burden:</b> {', '.join(burden_parts)}"
                    elements.append(Paragraph(burden_text, self.styles['BodyText']))
            
            # Separator between trials
            if i < len(trials):
                elements.append(Spacer(1, 12))
        
        return elements
    
    def _build_footer(self, dataset_version: str) -> List:
        """Build document footer"""
        elements = []
        
        elements.append(Spacer(1, 20))
        
        # Disclaimer
        disclaimer = (
            "<b>Disclaimer:</b> This report is for educational purposes only and does not "
            "determine trial eligibility. Final eligibility must be confirmed by the trial site."
        )
        elements.append(Paragraph(disclaimer, self.styles['BodyText']))
        elements.append(Spacer(1, 8))
        
        # Version info
        version_info = (
            f"Generated by TrialScout on {datetime.now().strftime('%B %d, %Y')} | "
            f"Dataset version {dataset_version} | "
            "Learn more at trialscout.com"
        )
        small_style = ParagraphStyle(
            name='SmallText',
            parent=self.styles['BodyText'],
            fontSize=7,
            textColor=colors.HexColor('#999999')
        )
        elements.append(Paragraph(version_info, small_style))
        
        return elements
    
    def generate_brief_base64(
        self,
        patient_profile: PatientProfile,
        matched_trials: List[MatchedTrial],
        top_n: int = 5,
        dataset_version: str = "1.0"
    ) -> str:
        """
        Generate clinician brief and return as base64 string
        
        Returns:
            Base64 encoded PDF string
        """
        pdf_bytes = self.generate_brief(
            patient_profile,
            matched_trials,
            top_n,
            dataset_version
        )
        
        return base64.b64encode(pdf_bytes).decode('utf-8')